---
- name: "Updating client.json file"
  template:
   src: "client.json.j2"
   dest: "/etc/sensu/conf.d/client.json"
  with_items: "{{sensu_client_config}}"

- name: "Updating config.json file"
  template:
   src: "config.json.j2"
   dest: "/etc/sensu/config.json"
  with_items: "{{sensu_server_details}}"

  notify:
  - Restart sensu-client
